#!/bin/bash

set -o nounset -o errexit

echo ""
echo "Validating code formatting"
scripts/validate-format

echo ""
echo "Testing and generating documentation"
scripts/sbt clean coverage test doc coverageReport

echo ""
echo "Build finished"
echo ""
